version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd node
      - npm install
  build:
    commands:
      - echo Building the project...
      - npx webpack
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -al
      - cd ..
      - chmod +x .code-pipeline/scripts/ci.sh
      - bash .code-pipeline/scripts/ci.sh
      # - zip -r MyApp.zip node/dist
      # - zip -g MyApp.zip node/cloudformation.yml

artifacts:
  files:
    - 'node/dist/**/*'
    - 'node/cloudformation.yml'