version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ls -al
      - cd ~
      - ls -al
      - cd node
      - npm install
  build:
    commands:
      - echo Building the project...
      - npx webpack
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -al
      - chmod +x .code-pipeline/scripts/ci.sh
      - bash .code-pipeline/scripts/ci.sh

artifacts:
  files:
    - 'dist/**/*'
  base-directory: 'dist'

cache:
  paths:
    - 'node_modules/**/*'